// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/data/cmszfs1/user/wadud/aNTGCmet/aNTGC_analysis/jetFakes/fitter/./estimateFake.C";

#endif
